### PR TITLE
Options to disable biters damage while flying

### PR DESCRIPTION
**Pull request by umanamente**
This change adds these configurable options:
* Disable damage from biters (in flight) - **default: on**
* Disable damage from acid puddles (in flight) - **default: on**
* Disable damage from spitter projectiles (in flight) - **default: off**

It doesn't make sense for a flying helicopter to take damage from acid puddles on the ground, or biters melee attacks. 

Also replaced all tabs with spaces.

### CODE REVIEW

**Comment by wolfhowlmedia** [comment]
Hello!
I know this comment is a little bit on the late side, but... 

As much as I like the gesture of adding additional functionality into the mod, I can't accept a PR that re-formats all files. Yes, I know that battle between spaces and tabs is still a thing after who knows how many decades, but that's not how people approach open-source projects. It's not how people do things in bigger companies either. You don't change spaces to tabs just because you prefer one over the other, but you continue with already establish formatting.

Imagine larger projects getting PRs consisting of 100s of files just because a single person prefers one style over the other.

Additional drawback of these kind of commits is that some malicious code can sneak into these giant diffs.

So, while the first commit will definitely not be included, I can cherry-pick the actual one, or close the PR altogether.

Let me know.

**Comment by umanamente** [comment]
Makes sense.
The reason I changed all tabs to spaces is that my IDE is configured to replace all tabs to spaces automatically, and I haven't seen a project with tabs in ages, so I thought maybe that was just a thing of a past and needs refactoring.

If you could cherry-pick just the second commit, that would be great (keep in mind that there are spaces instead of tabs).

**Comment by foonix** [comment]
I wound up investigating this a bit before realizing there is a fix in the test branch, but here's some findings that might help?

A good way to disable the acid "fire" is just override in the prototype:

```
    trigger_target_mask = { "common" },
```

The default for `car` is `{ "common", "ground-unit" }`, and the "fire" puddles are the only thing that I could find that specifies `"ground-unit"` but not `"common"`.

I tested this and it prevents the acid stickers from attaching when flying over a puddle.  Spitters will still attack and direct damage from the projectile still works.  The acid stickers from projectiles themselves are applied.  

Unfortunately it doesn't solve melee attack damage.

The two forum links [in the docs](https://lua-api.factorio.com/latest/types/TriggerTargetMask.html) contain some useful explanation.  Earendel's comment about implementing "flying" entities may be another avenue for investigation.  (The Space Exploration jetpack still has the problem with melee biters being able to attack.)

**Comment by wolfhowlmedia** [comment]
Yeah, this is a little bit of a weird one... I cherry-picked the relevant patch to the testing branch, because of the whitespace changes as well as some additions. I'm going to keep this PR open until testing branch is merged back into master. Additional comments and info is always welcome. Thank you.

> A good way to disable the acid "fire" is just override in the prototype:

I was actually wondering about that... how did Earendel solve this issue as well as one other: Flying above wires; I saw people were having issues with that as well, but as far as I could see,this may be due to modular structure of the mod...

But I'm rambling now. Thanks for additional info; Always welcome!

**Comment by wolfhowlmedia** [comment]
Merged into master

**Pull request closed without merging**
